version: '3.5'
services:
  openvpn:
    build: .
    container_name: ddns
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DDNS_ROUTE53_ZONE_ID: ${DDNS_ROUTE53_ZONE_ID}
      DDNS_ROUTE53_RECORD_SET: ${DDNS_ROUTE53_RECORD_SET}
      DDNS_ROUTE53_TTL: 60

